#!/usr/bin/env bash

#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=1-00:00:00  # Adjust time as necessary
#SBATCH --job-name=svg_plots_assemblies
#SBATCH --mail-user=federico.silvagutierrez@unifr.ch
#SBATCH --mail-type=ALL
#SBATCH --output=/data/users/fsilvagutierrez/03_Semester/assembly_course_2024/Output/output_svg_%j.o
#SBATCH --error=/data/users/fsilvagutierrez/03_Semester/assembly_course_2024/Error/error_svg_%j.e
#SBATCH --partition=pibu_el8



# Define work directory and paths
WORKDIR="/data/users/fsilvagutierrez/03_Semester/assembly_course_2024"
CONTAINER_GFAVIZ="/containers/apptainer/gfaviz_1.0.0.sif"

OUTPUT_DIR_READS_ASSEMBLY_FLYE="$WORKDIR/Assembly/Flye"
OUTPUT_DIR_READS_ASSEMBLY_HIFIASM="$WORKDIR/Assembly/Hifiasm"
OUTPUT_DIR_READS_ASSEMBLY_LJA="$WORKDIR/Assembly/LJA/Rld-2.asm"
OUTPUT_DIR_READS_ASSEMBLY_TRINITY="$WORKDIR/Assembly/Trinity"


# Visualize the assembly graph generated by FLYE using gfaviz.
apptainer exec  --no-home --bind "$WORKDIR" "$CONTAINER_GFAVIZ" gfaviz-mrtomrod --no-gui --render --labels --output "$OUTPUT_DIR_READS_ASSEMBLY_FLYE/assembly_graph.gfa.svg" "$OUTPUT_DIR_READS_ASSEMBLY_FLYE/assembly_graph.gfa"

# Visualize the assembly graph generated by HIFIASM using gfaviz.
apptainer exec  --no-home --bind "$WORKDIR" "$CONTAINER_GFAVIZ" gfaviz-mrtomrod --no-gui --render --labels --output "$OUTPUT_DIR_READS_ASSEMBLY_HIFIASM/Rld-2.asm.bp.p_ctg.gfa.svg" "$OUTPUT_DIR_READS_ASSEMBLY_HIFIASM/Rld-2.asm.bp.p_ctg.gfa"
apptainer exec  --no-home --bind "$WORKDIR" "$CONTAINER_GFAVIZ" gfaviz-mrtomrod --no-gui --render --labels --output "$OUTPUT_DIR_READS_ASSEMBLY_HIFIASM/Rld-2.asm.bp.hap1.p_ctg.gfa.svg" "$OUTPUT_DIR_READS_ASSEMBLY_HIFIASM/Rld-2.asm.bp.hap1.p_ctg.gfa"
apptainer exec  --no-home --bind "$WORKDIR" "$CONTAINER_GFAVIZ" gfaviz-mrtomrod --no-gui --render --labels --output "$OUTPUT_DIR_READS_ASSEMBLY_HIFIASM/Rld-2.asm.bp.hap2.p_ctg.gfa.svg" "$OUTPUT_DIR_READS_ASSEMBLY_HIFIASM/Rld-2.asm.bp.hap2.p_ctg.gfa"


# Visualize the assembly graph generated by LJA using gfaviz.
apptainer exec  --no-home --bind "$WORKDIR" "$CONTAINER_GFAVIZ" gfaviz-mrtomrod --no-gui --render --labels --output "$OUTPUT_DIR_READS_ASSEMBLY_LJA/mdbg.gfa.svg" "$OUTPUT_DIR_READS_ASSEMBLY_LJA/mdbg.gfa"


echo "Step: Assembly graph visualization completed."



echo "svg complete."